### ISSUE TITLE
some places need be modified in pcanet.py for Python 3

### ISSUE THREAD

**Issue by shu-hai** [styleNie/PCANet_python#1]
Hi, Nie,
When I import pcanet, there occurs the following error: 
```
>>> import pcanet.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rsrch2/biostatistics/hshu/PCAnet_python/PCANet_python-master/PCANet/pcanet.py", line 51
    OutImg.append( V[:,j].T.dot(im).reshape(ImgX,ImgY,1L) )
                                                       ^
SyntaxError: invalid syntax
```
I was wondering whether "1L" in the reshape() function should be "1"?

**Comment by styleNie** [comment]
I've tried both, and have no error.
I tried in windows with numpy=1.8.1, scipy=1.6.1, scikit-learn=0.18.

import sys
sys.path.append("C:\\Users\\Administrator\\Downloads\\PCANet_python-master\\PCANet")
import pcanet

I guess it's character typesetting problems, you can edit it again.

**Comment by shu-hai** [comment]
Is that OK to just replace "1L" by "1" in that line?
Sorry, I am a python beginner.

**Comment by styleNie** [comment]
you can try to replace "1L" by "1" in that line and run again to see if there is additional information displayed.
please feel free to contact me

**Comment by shu-hai** [comment]
My python version is 3.5.1., it only allows "1" in reshape() rather than "1L", but the code is OK for version 2.7.11. Thanks.

**Comment by shu-hai** [comment]
In lines 80 and 91 of pcanet.py, the usage of "assert" is not correct. It should be like
` assert len(PCANet.NumFilters)==PCANet.NumStages, 'Length(PCANet.NumFilters)~=PCANet.NumStages' `

In line 62, the "shuffle" function from module  "random" can not apply to "range" object in Python 3 (my version is 3.5.1.), it should be
```
    RandIdx = range(ImgZ)
    listInd = list(RandIdx)
    shuffle(listInd)
    RandIdx=listInd[:NumRSamples]
```
Finally, in line 142, please change "/" to "//", otherwise it will not be integer in Python 3.

**Comment by styleNie** [comment]
Thank you for your practical advice, I forgot to  mention that I wrote this code in python2.7

**Comment by shu-hai** [comment]
In line 43 of pcanet.py, please change '/' to '//' for Python 3.

**Comment by styleNie** [comment]
thank you , I have repaired it
